version: '3'
services:
  frontend:
    build:
      context: angular-frontend
    image: inventory-manager-frontend
    ports:
      - "4300:80"
  api:
    # Todo: Set up HTTPS
    build:
      context: dotnet-backend
    image: inventory-manager-api
    ports:
      - "4301:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
  mongo:
    image: mongo
    restart: always
