version: '3'
services:
  frontend:
    build:
      context: InventoryManager.Angular
    image: inventory-manager-frontend
    ports:
      - "4200:80"
  api:
    # Todo: Set up HTTPS
    build: ./InventoryManager.Api/
    image: inventory-manager-api
    ports:
      - "4201:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  mongo:
    image: mongo
    restart: always
